{
    'Vegan': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'vegan\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Gluten Free': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'gluten\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Sugar Free': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'sugar-free\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Talla': {'selector': 'div#características, div.mktpl-add-cart select[name*=\'size\'], div.mktpl-add-cart .variation-selector.size', 'default_value': '', 'found_value': None},
    'Etapa': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Tipo de piel': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Tipo de cabello': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Tono / Color': {'selector': 'div#características, div.mktpl-add-cart .color-swatch, div.mktpl-add-cart select[name*=\'color\']', 'default_value': '', 'found_value': None},
    'Acabado': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Cobertura': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Formato cosmético': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Función / Beneficio': {'selector': 'div#descripción, div#características', 'default_value': '', 'found_value': None},
    'Duración / Resistencia al agua': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Con fragancia (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Con protección solar (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'FPS': {'selector': 'div#características, div#descripción, h1 + span.fps, .product-detail-container__title + span.fps', 'default_value': '', 'found_value': None},
    'Ingredientes activos': {'selector': 'div#descripción ul, div#características ul, div#descripción .ingredients, div#características .ingredients', 'default_value': '', 'found_value': None},
    'Edad recomendada / Etapa bebé': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Formato bebé': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Hipoalergénico / Dermatológicamente probado (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'hypoallergenic\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Con ingredientes naturales (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'natural\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Sin conservantes (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Material / Textura bebé': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Antiderrames / Anticólicos / Antibacteriano (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Con BPA (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'bpa-free\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Compatible con esterilizadores (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Facilidad de digestión (Sí / No / Alta / Media / Baja)': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Con alcohol (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Protección 24h / Resistente al agua (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Con color (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Zonas de uso': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Libre de alcohol (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'alcohol-free\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Libre de aceites (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'oil-free\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Libre de parabenos (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'paraben-free\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Libre de comedogénicos (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Con enjuague (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Orgánico (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'organic\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Natural (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'natural\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Sin aditivos (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Vegetariano (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'vegetarian\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Keto (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'keto\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Bajo en sodio (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Fuente de proteína (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Fuente de fibra (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Fuente de vitaminas (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Apto para diabéticos (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Apto para celíacos (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Con edulcorantes naturales (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Con edulcorantes artificiales (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Función hogar': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Fragancia hogar': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Biodegradable (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Reutilizable (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Compatible con lavavajillas / microondas / mascotas / superficies': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Durabilidad / Resistencia': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Uso (Interior / Exterior)': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Sabor o aroma (para mascotas o alimentos)': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Beneficio para mascotas': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Tipo de suplemento': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Objetivo / Beneficio deportivo': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Sabor deportivo': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Presentación suplemento': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Con cafeína (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'},
    'Sin lactosa (Sí / No)': {'selector': 'div#características, div#descripción, app-mktpl-product-detail [class*=\'lactose-free\']', 'default_value': 'No', 'found_value': 'Sí'},
    'Certificaciones': {'selector': 'div#características, div#descripción, .certifications img', 'default_value': '', 'found_value': None},
    'Forma de consumo': {'selector': 'div#descripción, div#características', 'default_value': '', 'found_value': None},
    'Incluye accesorios (Sí / No)': {'selector': 'div#descripción, div#características', 'default_value': 'No', 'found_value': 'Sí'},
    'Tipo de deporte': {'selector': 'div#características, div#descripción', 'default_value': '', 'found_value': None},
    'Compatibilidad con apps, máquinas o rutinas (Sí / No)': {'selector': 'div#características, div#descripción', 'default_value': 'No', 'found_value': 'Sí'}
}